/*
CREATE SCHEMA nutrition;
*/

select current_schema();

CREATE TABLE nutrition.users(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	daily_cal_limit INT NOT NULL CHECK(daily_cal_limit>0),
	weekly_cal_limit INT NOT NULL CHECK(weekly_cal_limit>0),
	create_at TIMESTAMP DEFAULT now(),
	role TEXT NOT NULL DEFAULT 'app_user' CHECK(role in ('app_admin','app_user'))
);

select * from nutrition.users;
alter table nutrition.users add column role TEXT NOT NULL DEFAULT 'app_user' CHECK(role in ('app_admin','app_user'));


CREATE TABLE nutrition.products(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	calories_per_portion INT NOT NULL CHECK(calories_per_portion>0),
	portion_size NUMERIC(6,2) NOT NULL CHECK(portion_size>0),
	portion_unit TEXT NOT NULL CHECK(portion_unit in('g','kg','ml','l','pcs','г','кг','мл','л','шт')),
	protein NUMERIC(5,2) NOT NULL CHECK(protein>=0),
	fat NUMERIC(5,2) NOT NULL CHECK(fat>=0),
	carbs NUMERIC(5,2) NOT NULL CHECK(carbs>=0),
	created_by INT REFERENCES nutrition.users(id),
	is_public BOOLEAN DEFAULT FALSE
);



CREATE TABLE nutrition.menu_items(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL REFERENCES nutrition.users(id) ON DELETE CASCADE,
	product_id INT NOT NULL REFERENCES nutrition.products(id),
	UNIQUE(user_id,product_id)
);


CREATE TABLE nutrition.weekly_menu(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL REFERENCES nutrition.users(id) ON DELETE CASCADE,
	week_start DATE NOT NULL,
	created_at TIMESTAMP DEFAULT now(),
	UNIQUE(user_id, week_start)
);


CREATE TABLE nutrition.daily_menu(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	weekly_menu_id INT NOT NULL REFERENCES nutrition.weekly_menu(id) ON DELETE CASCADE,
	menu_date DATE NOT NULL,
	UNIQUE(weekly_menu_id,menu_date)
);

CREATE TABLE nutrition.consumed_food(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	daily_menu_id INT NOT NULL REFERENCES nutrition.daily_menu(id) ON DELETE CASCADE,
	product_id INT NOT NULL REFERENCES nutrition.products(id),
	quantity NUMERIC(6,2) NOT NULL DEFAULT 1 CHECK (quantity>0)
);

CREATE TABLE nutrition.weight_history(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL REFERENCES nutrition.users(id) ON DELETE CASCADE,
	weight NUMERIC(5,2) NOT NULL CHECK (weight>0),
	record_date DATE NOT NULL,
	UNIQUE(user_id,record_date)
);

CREATE INDEX idx_menu_items_user ON nutrition.menu_items(user_id);
CREATE INDEX idx_weekly_menu_user ON nutrition.weekly_menu(user_id);
CREATE INDEX idx_daily_menu_date ON nutrition.daily_menu(menu_date);
CREATE INDEX idx_weight_user_date ON nutrition.weight_history(user_id, record_date);

























