REVOKE ALL ON FUNCTION nutrition.get_my_profile() FROM PUBLIC, app_admin,app_user;
REVOKE ALL ON FUNCTION nutrition.update_my_profile(INT, INT) FROM PUBLIC,app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_weight_history() FROM PUBLIC,app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.add_weight_record(DATE, NUMERIC) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_available_products() FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.create_product(TEXT, INT, NUMERIC, TEXT, NUMERIC, NUMERIC, NUMERIC, BOOLEAN) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.update_product(INT, TEXT, INT, NUMERIC, TEXT, NUMERIC, NUMERIC, NUMERIC, BOOLEAN) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.delete_product(INT) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.import_products(JSONB) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.export_products() FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.add_product_to_menu(INT) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.remove_product_from_menu(INT) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.add_consumed_food(INT, NUMERIC, DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.remove_consumed_food(INT) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_daily_consumption(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_calorie_progress(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.generate_weekly_menu(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_weekly_menu(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_daily_menu(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.regenerate_day(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_daily_report(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_weekly_report(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.get_weight_report(DATE) FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.export_user_data() FROM PUBLIC, app_admin, app_user;
REVOKE ALL ON FUNCTION nutrition.import_user_data(JSONB) FROM PUBLIC, app_admin, app_user;
